---
title: "Demo 22/8"
author: "Johannes Rajala"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(anon)
library(randomForest)
```

# Aineiston hajontakuviot

## k-anonymiteeti

```{r}
data("iris")
kanon = kAnon(iris, 5)
par(mfrow=c(1,2))
plot(iris, col = as.factor(iris$Species))
plot(kanon, col = as.factor(kanon$Species))
```
```{r}
prediction_plot(iris, 5, kanon)
```

## l-diversiteetti


```{r}
ldiv = lDiversity(iris, sensitiveAttributes = "Species", l = 2, k = 5)
par(mfrow=c(1,2))
plot(iris, col = as.factor(iris$Species))
plot(ldiv, col = as.factor(ldiv$Species))
```

```{r}
prediction_plot(iris, 5, ldiv)
```

## RSA

```{r}
rsa = encrypt(iris)
par(mfrow=c(1,2))
plot(iris, col = as.factor(iris$Species))
plot(rsa, col = as.factor(rsa$Species))
```

```{r}
rsa[,5] = as.factor(rsa[,5])
prediction_plot(iris, 5, rsa)
```

## Spectral

### Kohina

```{r}
noise = spectral(iris, function(x) sensitive_noise(x, 5), "UD", shuffle = FALSE)
par(mfrow=c(1,2))
plot(iris, col = as.factor(iris$Species))
plot(noise, col = as.factor(noise$Species))
```

```{r}
prediction_plot(iris, 5, noise)
```

```{r}
reidentification_rate(iris, noise)
```

### Sarakepermutaatio

```{r}
swap = spectral(iris, cell_swap, "U")
par(mfrow=c(1,2))
plot(iris, col = as.factor(iris$Species))
plot(swap, col = as.factor(swap$Species))
```

```{r}
prediction_plot(iris, 5, swap)
```

# Käytettävyyden tarkastelu

## Satunnaismetsä

```{r}
set.seed(22889)
samples = sample(c(FALSE,TRUE), nrow(iris), replace = TRUE, prob = c(0.2, 0.8))
train = iris[samples, ]
test = iris[!samples, ]

rf = randomForest(Species ~., data = train)
reference = mean(predict(rf, test[, 1:4]) == test[,5])
cat("Anonymisoimattoman aineiston luokittelutarkkuus testidatalla:" , reference) 
```

### k-anonymiteetti

```{r}
kanon = kAnon(train, 5)
```
```{r}
rf = randomForest(Species ~., data = kanon)
cat("Osumatarkkuus:", mean(predict(rf, test[, 1:4]) == test[,5]), "Osuus anonymisoimattomasta luokittelutarkkuudesta:", mean(predict(rf, test[, 1:4]) == test[,5]) / reference)
```

### l-diversiteetti

```{r}
ldiv = lDiversity(train, "Species" , 2)
```

```{r}
rf = randomForest(Species ~., data = ldiv)
cat("Osumatarkkuus:", mean(predict(rf, test[, 1:4]) == test[,5]),"Osuus anonymisoimattomasta luokittelutarkkuudesta:", mean(predict(rf, test[, 1:4]) == test[,5]) / reference)
```
### RSA

```{r}
rsa = encrypt(iris)
train_rsa = rsa[samples, ]
test_rsa = rsa[!samples, ]
```

```{r}
rf = randomForest(as.factor(Species) ~., data = train_rsa)
cat("Osumatarkkuus:", mean(predict(rf, test_rsa[, 1:4]) == test_rsa[,5]),"Osuus anonymisoimattomasta luokittelutarkkuudesta:", mean(predict(rf, test_rsa[, 1:4]) == test_rsa[,5]) / reference)
```


### Spektraalinen kohina

```{r}
noise = spectral(train, function(x) sensitive_noise(x, 5), "UD")
```

```{r}
rf = randomForest(as.factor(Species) ~., data = noise)
cat("Osumatarkkuus:", mean(predict(rf, test[, 1:4]) == test[,5]),"Osuus anonymisoimattomasta luokittelutarkkuudesta:", mean(predict(rf, test[, 1:4]) == test[,5]) / reference)
```

### Spektraalinen sarakepermutaatio

```{r}
swap = spectral(train, cell_swap, "U")
```

```{r}
rf = randomForest(as.factor(Species) ~., data = swap)
cat("Osumatarkkuus:", mean(predict(rf, test[, 1:4]) == test[,5]),"Osuus anonymisoimattomasta luokittelutarkkuudesta:", mean(predict(rf, test[, 1:4]) == test[,5]) / reference)
```
