---
title: "Demo Cosmos"
author: "Johannes Rajala"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(anon)

library(randomForest)
library(pROC)
COSMOS_HDS2 <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/COSMOS_HDS2.csv")
```

```{r, include=FALSE}
set.seed(1288)
cols = c("headache_FU", 
          "Age", "Gender",   "sf12gr", "Depression",  "Bmi", 
          "traffic3_min_hf")
          #"tinnitus_baseline", "tinnitus_FU",
          #"hearloss_base_fin", "hearloss_follow_fin",
          # "day_head_follow")

# "hit_score_r","Alamount", "S01MPH0101", "agefirstmpuse", "numbermpyears",          "sevhead", 


# tarvitaan:
# age, gender, country, Painkiller, sf12v2, Depression, Mos-sleep, education, BMI, smoking, alcohol total consumption, hypertension

# mph0101 weekly mobilephone use
subset = COSMOS_HDS2[, cols]

# Drop sevhead == 1 rows 
#subset = subset[ subset$sevhead !=  1,]
# Drop sevhead col
#subset$sevhead = NULL

data_omit = na.omit(subset)
empty_cells <- data_omit == "" | data_omit == " "
data_clear = data_omit[empty_cells] <- NA
data_omitted = na.omit(data_clear)
droprows = c("73", "74", "187", "317", "412", "417", "851", "1375", "1445", "1613", "1626", "1661", "1677", "1887", "2455", "2594", "3226")
data = na.omit(data_omit[!(rownames(data_omit) %in% droprows), ])

# encode response variable from 0,1 to no,yes
data$headache_FU = ifelse(data$headache_FU == 1, "Yes", "No")


index = sample(c(TRUE, FALSE), nrow(data), TRUE, prob = c(0.8, 0.2))
train = data[index, ]
test = data[!index, ]

kanon_bin <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/kanon_bin", row.names=1)
ldiv_bin <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/ldiv_bin", row.names=1)
noise_bin = read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/noise_bin", row.names=1)
swap_bin = read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/swap_bin", row.names=1)
rsa_bin = read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/rsa_bin", row.names=1)
```

# Referenssi

```{r}
glm = glm(as.factor(headache_FU) ~., data = train, family = "binomial")
summary(glm)
preds = predict(glm, test[,-1])

```

```{r eval=FALSE, include=FALSE}
star = stargazer::stargazer(glm, type = "text")
writeLines(capture.output(broom::tidy(glm)), "model_summary_broom.txt")
writeLines(star, "model_summary_star.txt")
preds = predict(glm, test[,-1])

```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

# $k$-anonymiteetti


```{r}
glm_k = glm(as.factor(headache_FU) ~., data = kanon_bin, family = "binomial")
summary(glm_k)
preds = predict(glm_k, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```



# $l$-diversiteetti

```{r}
glm = glm(as.factor(headache_FU) ~., data = ldiv_bin, family = "binomial")
summary(glm)
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```




# Spektraalinen

## Kohina

```{r}
glm = glm(as.factor(headache_FU) ~., data = noise_bin, family = "binomial")
summary(glm)
preds = predict(glm, test[,-1])
#reidentification_rate(train, noise_bin)
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```



## Sarakepermutaatio

```{r}
glm = glm(as.factor(headache_FU) ~., data = swap_bin, family = "binomial")
summary(glm)
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

























