---
title: "Kuvaajavertailu"
author: "Johannes Rajala"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(anon)
```



```{r}
swap = spectral(iris, cell_swap)
swapt = spectral(iris, cell_swap, approx = TRUE)
par(mfrow = c(3,1))
plot(iris, col = as.factor(iris[,5]))
plot(swap, col = as.factor(swap[,5]))
plot(swapt, col = as.factor(swapt[,5]))

```


```{r}
set.seed(12)
# Generate a lower triangular matrix
lower_triangular <- matrix(rnorm(16), nrow = 4)

# Create a positive definite matrix using Cholesky decomposition
positive_definite_matrix <- lower_triangular %*% t(lower_triangular)

testi = as.data.frame(MASS::mvrnorm(n = 1000, c(10,2,-5,16), positive_definite_matrix))
```

```{r}
plot(testi)
```

```{r}
svd = svd(testi, 1000, 4)

colmeans = colMeans(svd$u)
cov = (t(svd$u- colmeans) %*% (svd$u - colmeans))

cor = cov2cor(cov)

```

```{r}
anon::prediction_plot( prediction_all(iris, 5, swap))
```


# samankaltaisuus, histogrammit, density plotit aineistoille := korrelaatiomatriiseja anonyymille ja oglle (numeeriset ok) kategoriselle
# mittaukset anonymisoijan näkökulmasta (eli tetaa og datalla opetettu malli)'
# esim violinplot
# hajontakuviot jos ok
# utility, privacy hyperparamter (noise) plot




```{r}
noise = spectral(iris, sensitive_noise)
reidentification_rate(iris, noise)
```

```{r}
plot(noise, col = as.factor(noise[,5]))
```



```{r}
plot(iris)
```






