---
title: "Demo Cosmos"
author: "Johannes Rajala"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(anon)
library(randomForest)
library(pROC)
COSMOS_HDS2 <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/COSMOS_HDS2.csv")
```

```{r, include=FALSE}
set.seed(1288)
cols = c("headache_FU", 
          "Age", "Currsmoker", "Bmi", "Gender", "Depression", "S01MPH0101", "agefirstmpuse", "numbermpyears",  "Alamount", "sf12gr",
          "sevhead", "sevhead_R",
           "hit_score_r",       
          "tinnitus_baseline", "tinnitus_FU",
          "traffic3_min_hf", "Traffic3_min_hf_r", 
          "hearloss_base_fin", "hearloss_follow_fin",
           "day_head_follow")
subset = COSMOS_HDS2[, cols]

# Drop sevhead == 1 rows 
subset = subset[ subset$sevhead !=  1,]
# Drop sevhead col
subset$sevhead = NULL

data_omit = na.omit(subset)
empty_cells <- data_omit == "" | data_omit == " "
data_clear = data_omit[empty_cells] <- NA
data_omitted = na.omit(data_clear)
droprows = c("73", "74", "187", "317", "412", "417", "851", "1375", "1445", "1613", "1626", "1661", "1677", "1887", "2455", "2594", "3226")
data = na.omit(data_omit[!(rownames(data_omit) %in% droprows), ])

# encode response variable from 0,1 to no,yes
data$headache_FU = ifelse(data$headache_FU == 1, "Yes", "No")


index = sample(c(TRUE, FALSE), nrow(data), TRUE, prob = c(0.8, 0.2))
train = data[index, ]
test = data[!index, ]

kanon <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/kanon", row.names=1)
ldiv <- read.csv("C:/Users/Johannes/Desktop/Gradu/DATA/ldiv", row.names=1)
```

# Referenssi

```{r}
glm = glm(as.factor(headache_FU) ~., data = train, family = "binomial")
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

# $k$-anonymiteetti


```{r}
glm = glm(as.factor(headache_FU) ~., data = kanon, family = "binomial")
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

```{r}
prediction_plot(train, 5, kanon)
```


# $l$-diversiteetti

```{r}
glm = glm(as.factor(headache_FU) ~., data = ldiv, family = "binomial")
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

```{r}
prediction_plot(train, 5, ldiv)
```


# Spektraalinen

## Kohina

```{r}
noise = spectral(data, function(x) sensitive_noise(x, 3), on_matrices = "UD", shuffle = FALSE)

glm = glm(as.factor(headache_FU) ~., data = noise, family = "binomial")
preds = predict(glm, test[,-1])
reidentification_rate(data, noise)
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

```{r}
prediction_plot(train, 5, noise)
```

## Sarakepermutaatio

```{r}
swap = spectral(data, cell_swap)

glm = glm(as.factor(headache_FU) ~., data = swap, family = "binomial")
preds = predict(glm, test[,-1])
```


```{r}
roc = roc(test[,1], preds)
plot(roc)
auc(roc)
```

```{r}
prediction_plot(train, 5, swap)
```

# RSA

```{r}
rsa = encrypt(data)
rsa_train = rsa[index, ]
rsa_test = rsa[!index, ]

glm = glm(as.factor(headache_FU) ~., data = rsa_train, family = "binomial")
preds = predict(glm, rsa_test[,-1])
```

```{r}
roc = roc(rsa_test[,1], preds)
plot(roc)
auc(roc)
```

























